### ISSUE TITLE
enemy

### ISSUE THREAD

**Issue by ajlopez4** [annoyatron255/Game#6]
Hi, 

I'm trying to get back into programming and I'm trying to understand your game. How do you get the enemy to follow the other guy? 

Thank you,
Alex

**Comment by annoyatron255** [comment]
I have been working the organization in a he past few weeks, but in this version, the enemy as has been lazily pushed at the bottom of Sprite.cpp. It works by checking if it is left or right of the player, then changing the x axis accordingly. It does the same for up and down, this time changing the y axis. Keep in mind in SDL/SDL2 (0,0) is at the top left corner and only has positive numbers. To get back into programming I recommand LazyFoo's SDL2 tutorials.
